name: 247phil
favicon: null
layout_spectrum: 0.24713
typography_spectrum: 0.06808
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0d08'
    - '#a09174'
    - '#e3d2ca'
    - '#554931'
    - '#2c2b26'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
